Feature/project api
albert118/Studio-Management-System pull request #52
Opened 2023-03-26 13:53 UTC by willyyto

2023-03-26 15:07 UTC, albert118 requested changes
Looks good overall! Let's just add some logging around those `try-catch` statements to avoid swallowing exceptions silently 😉

2023-03-26 15:07 UTC, albert118 commented on src/server/StudioManagementSystem.Infrastructure/Repositories/GroupRepositoryAsync.cs
> +        }
the find async may throw (same with the method that repeats this logic). Let's re-use the existing method, check we got the group, and add some logging

```suggestion
        var group = await GetGroupAsync(id, ct)
            ?? throw new DataException($"No {nameof(Group)} was found with the given ID '{id}'");

        try
        {
            group.Name = name;
            await _smsDbContext.SaveChangesAsync(ct);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, $`an error occurred while updating the {nameof(Group)} name`)
            return false;
        }
```

2023-03-26 15:07 UTC, albert118 commented on src/server/StudioManagementSystem.Infrastructure/Repositories/GroupRepositoryAsync.cs
> +        }
This means if we screw up in the rest of the app we'll quickly know,

* did we remember the ID?
* OR what was the unknown error we encountered?

2023-03-26 15:07 UTC, albert118 commented on src/server/StudioManagementSystem.Infrastructure/Repositories/GroupRepositoryAsync.cs
> +        }
I'd repeat this logging pattern in particular around the repo's

2023-03-26 15:07 UTC, albert118 commented on src/server/StudioManagementSystem/DependencyInjectionExtensions.cs
>      // private static ContainerBuilder AddMySpecialDbContext(this ContainerBuilder builder)
feel free to drop these comments now that we have real examples

2023-03-27 23:16 UTC, JaydenL33 commented
@albert118 @willyyto, if we are using Supabase for our Database, Auth and API Hosting, do we have any need for our C# backend?

2023-03-28 00:09 UTC, albert118 commented
> @albert118 @willyyto, if we are using Supabase for our Database, Auth and API Hosting, do we have any need for our C# backend?

I mean it’s already here and quick enough to use. Let’s have a chat Thursday night. Or earlier if you want to catch up on the project

2023-03-30 15:37 UTC, albert118 commented
## API

![image](https://user-images.githubusercontent.com/26985949/228889366-87cce521-ae00-4fc2-91eb-9a7720ff3448.png)

## Schemas

![image](https://user-images.githubusercontent.com/26985949/228889401-f4652323-308e-40e5-bd33-ddad649f101f.png)

2023-03-30 15:38 UTC, albert118 commented on src/server/StudioManagementSystem.Core/Entities/MySpecialObject.cs
removes related

2023-03-30 15:39 UTC, merged